version: "3.8"
services:
  app:
    build: .
    image: sampleapp
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    container_name: my-app
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
  app1:
    build: .
    image: sampleapp
    ports:
      - "3041:3000"
    environment:
      - PORT=3000
    container_name: my-app1
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

networks:
  my-net:
    driver: bridge
